export const routes = [
  { path: '/', title: 'Aino', bodyClass: 'home', pageClass: 'home-page' },
  { path: '/about', title: 'About', bodyClass: 'about', pageClass: 'about-page' },
  { path: '/contact', title: 'Contact', bodyClass: 'contact', pageClass: 'contact-page' },
  { path: '/journal', title: 'Journal', bodyClass: 'journal', pageClass: 'journal-page' },
  {
    path: '/journal/agentic-engineering',
    title: 'Agentic Engineering',
    bodyClass: 'journal-post',
    pageClass: 'journal-page',
  },
  { path: '/journal/test-topic', title: 'Test Topic', bodyClass: 'journal-post', pageClass: 'journal-page' },
  { path: '/play', title: 'Play', bodyClass: 'play play-hub', pageClass: 'play-page' },
  { path: '/play/textris', title: 'Textris', bodyClass: 'play textris', pageClass: 'play-page' },
  { path: '/play/snekst', title: 'Snekst', bodyClass: 'play snekst', pageClass: 'play-page' },
  { path: '/play/pakku', title: 'Pakku', bodyClass: 'play pakku', pageClass: 'play-page' },
  { path: '/services', title: 'Services', bodyClass: 'services', pageClass: 'services-page' },
  { path: '/services/centra', title: 'Centra', bodyClass: 'services services-centra', pageClass: 'services-page' },
  { path: '/services/design', title: 'Design', bodyClass: 'services services-design', pageClass: 'services-page' },
  { path: '/services/intelligence', title: 'Intelligence', bodyClass: 'services services-intelligence', pageClass: 'services-page' },
  { path: '/services/shopify', title: 'Shopify', bodyClass: 'services services-shopify', pageClass: 'services-page' },
  { path: '/work', title: 'Work', bodyClass: 'work', pageClass: 'work-page' },
  { path: '/work/all-blues', title: 'All Blues', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/beyond-medals', title: 'Beyond Medals', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/emmas', title: 'Emmas', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/eton-shirts', title: 'Eton Shirts', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/gardinex', title: 'Gardinex', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/gulled', title: 'Gulled', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/hunkydory', title: 'Hunkydory', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/molo', title: 'Molo', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/nudie-jeans', title: 'Nudie Jeans', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/samsoe-samsoe', title: 'Samsoe Samsoe', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/sandisk', title: 'Sandisk', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/socksss', title: 'Socksss', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/sweet-sktbs', title: 'Sweet SKTBS', bodyClass: 'case', pageClass: 'case-page' },
  { path: '/work/tinted', title: 'Tinted', bodyClass: 'case', pageClass: 'case-page' },
]

export const routeByPath = new Map(routes.map((route) => [route.path, route]))
